import PeopleRecallGame from "@/components/recall/PeopleRecallGame";
import RoutineRecallGame from "@/components/recall/RoutineRecallGame";
import TimelineRecallGame from "@/components/recall/TimelineRecallGame";

export default function RecallPage() {
  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 py-8 sm:py-10 space-y-6">
      <header>
        <h1 className="font-display text-3xl font-semibold tracking-tight text-foreground">Active Recall</h1>
        <p className="text-sm text-foreground/55 mt-2 max-w-2xl leading-relaxed">
          Three cognitive-stimulation games, generated by the Recall Agent directly from this patient&rsquo;s
          real Twin data — people, routines, and the actual detected-change timeline — not generic trivia.
          Retrieval practice (actively recalling something) is a well-studied way to reinforce memory, more
          effective than passive review.
        </p>
      </header>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-start">
        <PeopleRecallGame />
        <RoutineRecallGame />
        <TimelineRecallGame />
      </div>
    </div>
  );
}
